### ISSUE TITLE
Internet Yetu (Our Internet)

### ISSUE THREAD

**Issue by BrianObilo** [mozilla/global-sprint#334] opened 2018-05-11 17:54 UTC
**[ Project Contact ]** @BrianObilo
**[ GitHub Repo ]** https://github.com/BrianObilo/Internet-Yetu
**[ Track ]** Web Literacy, Openness, Internet Privacy, Digital Inclusion, 
**[ Location ]** Nairobi EAT +3
**[ Coach ]** @Wiroll & @psubhashish

### Description
We are a start up based in Nairobi Kenya. Internet Yetu directly translates to Our Internet in English. We firmly believe that affordable access to the Internet should be a basic human right. We strive towards supporting and advocating for digital inclusion, digital accessibility, web literacy,  data and big data literacy and web openness. Our startup aims to work toward increasing youth activity in Internet Governance.
***

## Want to contribute to this project during #mozsprint?
Join us at the Global Sprint, May 10-11. Leave a comment below if you're interested in contributing to this project during #mozsprint 2018!

***

## Note to the Project Lead :tada:
Congrats, @BrianObilo! This is your official project listing for the Mozilla Global Sprint 2018. To confirm your registration, please complete and check off the following:

- [ ] Complete [Open Leadership 101](https://mozilla.teachable.com/p/open-leadership-101)
- [x] Provide a GitHub repository for work and discussion on your project (in a comment or at the top of this issue)
- [ ] [Create a README file](https://mozilla.github.io/open-leadership-training-series/articles/opening-your-project/write-a-great-project-readme/) in your project repository. This file should help newcomers understand what your project is, why it's important, and kinds of help you're looking for.
- [ ] [Create file: LICENSE](http://choosealicense.com/) to give your project an open license, allowing for sharing and remixing.
- [ ] Turn on your [Issue Tracker](https://mozilla.github.io/global-sprint/project-lead-guide/templates/#4-create-issues) and create at least three issues to describe each task that you need help with and how a contributor can get started on that task.
- [ ] [Create a label](https://mozilla.github.io/global-sprint/project-lead-guide/templates/#5-add-a-mozsprint-label) called `mozsprint` and apply it to your issues.:

If you get stuck at any point, feel free to look at the [requirements page](https://mozilla.github.io/global-sprint/project-lead-guide/project-requirements/) and [project templates](https://mozilla.github.io/global-sprint/project-lead-guide/templates/) or reach out to your Project Coach, @Wiroll & @psubhashish. We're here to help you through this process.

**Comment by abbycabs** [comment] 2018-05-11 18:09
Hi @BrianObilo! This looks like a duplicate of #333  -- please use that issue! I'll close this in the meantime :)

**Closed as completed by abbycabs** 2018-05-11 18:09 UTC
