### ISSUE TITLE
PREreview 2.0: Building a community of reviewers for preprints

### ISSUE THREAD

**Issue by dasaderi** [mozilla/global-sprint#326] opened 2018-05-10 15:41 UTC
**[ Project Contact ]** @dasaderi
**[ GitHub Repo ]** https://github.com/SamanthaHindle/preprint_JournalClub
**[ Track ]** Openness, 
**[ Location ]** Cambridge UK, BST
**[ Coach ]** @quirksahern & @fimakeswork

### Description
PREreview seeks to diversify peer review in the academic community by crowdsourcing pre-publication feedback to improve the quality of published scientific output, and to train early-career researchers (ECRs) in how to review others' scientific work. 

During the #eLifeSprint #mozsprint we are developing a PREreview.org platform 2.0 with new features and completely open source.
Here is our working etherpad: https://etherpad.wikimedia.org/p/peerreview_elife_MVP

Daniela Saderi, Joe McArthur, Giuliano Maciocci, Joe Wass, Andre Marques-Smith, Nick Duffield, Felix Hoffmann, Daniel Ecer
***

## Want to contribute to this project during #mozsprint?
Join us at the Global Sprint, May 10-11. Leave a comment below if you're interested in contributing to this project during #mozsprint 2018!

***

## Note to the Project Lead :tada:
Congrats, @dasaderi! This is your official project listing for the Mozilla Global Sprint 2018. To confirm your registration, please complete and check off the following:

- [x] Complete [Open Leadership 101](https://mozilla.teachable.com/p/open-leadership-101)
- [x] Provide a GitHub repository for work and discussion on your project (in a comment or at the top of this issue)
- [ ] [Create a README file](https://mozilla.github.io/open-leadership-training-series/articles/opening-your-project/write-a-great-project-readme/) in your project repository. This file should help newcomers understand what your project is, why it's important, and kinds of help you're looking for.
- [ ] [Create file: LICENSE](http://choosealicense.com/) to give your project an open license, allowing for sharing and remixing.
- [ ] Turn on your [Issue Tracker](https://mozilla.github.io/global-sprint/project-lead-guide/templates/#4-create-issues) and create at least three issues to describe each task that you need help with and how a contributor can get started on that task.
- [ ] [Create a label](https://mozilla.github.io/global-sprint/project-lead-guide/templates/#5-add-a-mozsprint-label) called `mozsprint` and apply it to your issues.:

If you get stuck at any point, feel free to look at the [requirements page](https://mozilla.github.io/global-sprint/project-lead-guide/project-requirements/) and [project templates](https://mozilla.github.io/global-sprint/project-lead-guide/templates/) or reach out to your Project Coach, @quirksahern & @fimakeswork. We're here to help you through this process.

**Comment by arinbasu** [comment] 2018-05-11 00:44
Happy to join this project. I have already initiated a preprint journal club at the University of Canterbury and we discuss preprint articles, write about them (See https://journal.sketchingscience.org/inst/18975?articles_format=list, and https://arinbasu.github.io/UC-SHSS-Study-Group/list_of_papers.html); it’d be nice to get some recognition. Perhaps a project to build a database of these projects and a common format to organise preprint and recognition strategies would be worth spending time.

**Comment by andrefmsmith** [comment] 2018-05-11 10:43
Identified target users
Identified user stories for each
Ranked user stories by necessity for a minimum viable product:
- https://etherpad.wikimedia.org/p/peerreview_elife_MVP

**Comment by abbycabs** [comment] 2018-05-11 13:04
Hey @dasaderi - this looks like a duplicate of #271. Any reason why you have separate listing?

**Closed as completed** 2018-05-11 13:37 UTC
Labels: [Track] Openness, eLifeSprint

**Comment by dasaderi** [comment] 2018-05-11 14:55
eLIFE Innovation Sprint 2018

PREreview 2.0

In brief: PREreview: Putting the ‘peer’ back into peer review!
Aim: Design concepts for PREreview 2.0
We created: User stories and wireframes for a new PREreview experience
Achievements: used Design Thinking to kick start the new concept both technically and strategically 
TIL: Collaboration is awesome! 
What’s next? A lot of work to build the community and use technology to facilitate interaction and sharing

**Comment by dasaderi** [comment] 2018-05-11 22:52
@acabunoc it was not intentional. Sorry. :(

**Comment by npscience** [comment] 2018-05-17 14:33
@acabunoc this isn't a duplicate, this is the posting that relates to the specific work done at eLife Sprint. The other listing is more general for the PREreview project. Please could this one be re-opened? @dasaderi would you agree?

**Comment by npscience** [comment] 2018-05-17 14:37
@dasaderi do you have a timescale for when the documentation from the elife sprint work will go live on the main github repo, please? Not intended to push you for this, just wondering so we can know when and where to link to from our own blog about the sprint :)
