### ISSUE TITLE
Activismo Lenguas: a online resource exchange for language digital activism 

### ISSUE THREAD

**Issue by GuteMonik** [mozilla/global-sprint#313] opened 2018-05-09 18:24 UTC

**Comment by abbycabs** [comment] 2018-05-09 18:29
Hi @GuteMonik! This seems to be a duplicate of #150 -- please use #150! I'll be closing this.

**Closed as completed by abbycabs** 2018-05-09 18:29 UTC

**Comment by itzelmv** [comment] 2018-09-10 15:43
Hi Monica! 

It is a great  honor to meet you. I  want to apologize for the delay to answer you. I was confused with my message on Github. In the other   hand,  last weekend I was sent to a community without Phone ines or  bad connectivity.  There will be no more work out of the city. I am so  happy that a person with such a high level as yours, be  my mentor. Thank you  for your time. I think the work that you develop is so important, thank you so much for sharing part of your experience with me . The issue of inclusion is my life. Not only because I work with Deaf communities but also because I am a  hearing loss person. I can hear and communicate perfectly thanks to all the support I have received, but this is not the case in most of Mexico's metropolitan communities. Your work in Latin America is so interesting. I would love to know more. I believe that it  is so necessary  for indigenous communities whose language loses more and more prestige in a community that does not understand its linguistic value. In addition to poverty and serious  community needs. I have worked with homeless deaf people, and I believe they need empowerment and more inclusive means. It really is a great honor and a life opportunity for me that MonzillaFest and your kind person  be interested in my proposal since today, much of the communication of the deaf  is by  internet media.  I want ti ask you if It is possible to schedulle a day yo contact each other. 
Itzel





Thank you so much again,
